blog/apps/authuser/urls.py
from django.urls import path
from . import views

app_name = 'usuario'

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logount_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('user/<int:id_value>', views.view_user, name='user'),
    path('user/delete/<int:id_value>', views.delete_user, name='delete')
]

blog/apps/news/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
    # URLs para noticias
    path('buscar/', views.search_results, name='search_results'),
    path('<int:post_id>', views.ver_noticia, name='ver_noticia'),
    path('comentarios/<int:post_id>', views.comment_post, name='comentarios'),
    path('comentarios/editar/<int:comment_id>', views.edit_comment, name='edit_comment'),
    path('comentarios/eliminar/<int:comment_id>', views.delete_comment, name='delete_comment'),
    path('noticia/borrar/<int:post_id>', views.delete_news, name='delete_news'),

    # URLs para categorías (para ser incluidas bajo el namespace 'categorias')
    path('lista/', views.category_list, name='category_list'),
    path('categoria/<int:category_id>/', views.news_by_category, name='news_by_category'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView # Importar TemplateView
from . import views
# Configurar página 'media' para imágenes subidas
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('acerca-de/', TemplateView.as_view(template_name='about.html'), name='about'), # Página Acerca de
    path('contacto/', TemplateView.as_view(template_name='contact.html'), name='contact'), # Página Contacto
    # Incluir las páginas definidas por las otras apps
    path('noticias/', include('apps.news.urls')),
    path('categorias/', include('apps.news.urls', namespace='categorias')), # URLs para categorías
    path('', include('apps.authuser.urls')),
    
]

# Agregar media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#Error pages
handler400 = views.bad_request
handler403 = views.access_denied
handler404 = views.page_not_found
handler500 = views.server_error

blog/templates/about.html
{% extends 'index.html' %}

{% block title %}Acerca de{% endblock title %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Acerca de BlogInfo2025</h1>
    <p class="lead">Este blog es un proyecto final del Informatorio 2025, creado por el Grupo 1 - Comisión 2.</p>
    <hr class="my-4">
    <p class="lead">Repositorio del proyecto: <a href="https://github.com/Enzostik/Blog_Informatorio2025" class="text-decoration-none h4 me-2"><i class="fab fa-github"></i></a></p>
    <hr class="my-4">
    <p class="lead">Integrantes del grupo:</p>
    <ul>
        <li>Almenar Enzo
            <a href="https://github.com/Enzostik" class="text-decoration-none h4 me-2"><i class="fab fa-github"></i></a>
            <a href="https://www.linkedin.com/in/enzo-naim-almenar-9205121a5/" class="text-decoration-none h4 me-2"><i class="fab fa-linkedin"></i></a>
        </li>
        <li>Ayala Lautaro
            <a href="https://github.com/LautaroA19" class="text-decoration-none h4 me-2"><i class="fab fa-github"></i></a>
        </li>
        <li>Irrito Alvarez
            <a href="https://github.com/AlvarezIrrito" class="text-decoration-none h4 me-2"><i class="fab fa-github"></i></a>
        </li>
    </ul>
</div>
{% endblock content %}

blog/templates/contact.html
{% extends 'index.html' %}

{% block title %}Contacto{% endblock title %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Contacto</h1>
    <p class="lead">¿Querés decirnos algo?</p>
    <hr class="my-4">
    <p>Podés contactarnos a través del siguiente correo electrónico:</p>
    <p class="h5">
        <a href="mailto:contacto@contacto.com" class="text-decoration-none">
            <i class="fa-solid fa-envelope"></i> contacto@contacto.com
        </a>
    </p>
    <p class="mt-4">También podés ver el repositorio del proyecto:</p>
    <ul class="list-inline">
        <li class="list-inline-item">
            <a href="#" class="text-decoration-none h4 me-2"><i class="fab fa-linkedin"></i></a>
        </li>
        <li class="list-inline-item">
            <a href="https://github.com/Enzostik/Blog_Informatorio2025" class="text-decoration-none h4 me-2"><i class="fab fa-github"></i></a>
        </li>
    </ul>
</div>
{% endblock content %}

blog/templates/error_page.html
{% extends "index.html" %}

{% block title %}{{ title_page }}{% endblock title %}

{% block content %}
    <h1>{{ header_page }}</h1>
    <p>{{ message }}</p>
    <ul>
        <a href={% url "home" %}>Volver a la página principal.</a>
    </ul>
{% endblock content %}

blog/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BlogInfo2025 | {% block title %}Página Principal{% endblock title %}</title>
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <!-- FontAwesome for icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    
    <!-- Favicon -->
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    
    <meta name="theme-color" content="#712cf9">
</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <i class="fa-solid fa-laptop-code"></i>
                    BlogInfo2025
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'categorias:category_list' %}">Categorías</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'about' %}">Acerca de</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact' %}">Contacto</a>
                        </li>
                    </ul>
                    
                    <form class="d-flex mx-auto" role="search" action="{% url 'noticias:search_results' %}" method="GET">
                        <input class="form-control me-2" type="search" placeholder="Buscar artículos..." aria-label="Buscar" name="q">
                        <button class="btn btn-outline-success" type="submit">
                            <i class="fa-solid fa-magnifying-glass"></i>
                        </button>
                    </form>
                    
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-solid fa-user"></i> {{ user.username }}
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'usuario:profile' %}">Mi Perfil</a></li>
                                    {% if user.is_staff %}
                                        <li><a class="dropdown-item" href="/admin/">Panel de Admin</a></li>
                                    {% endif %}
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'usuario:logout' %}">Cerrar Sesión</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'usuario:login' %}">Iniciar Sesión</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'usuario:register' %}">Registrarse</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="container mt-4 pt-5 flex-fill">
        {% block content %}
            <div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-label="Slide 1" aria-current="true"></button>
                    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class=""></button>
                    {% for n in numbers %}
                    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="{{n}}" aria-label="Slide {{n}}" class=""></button>
                    {% endfor %}
                    
                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active" style="height: 400px;">
                        <svg aria-hidden="true" class="bd-placeholder-img" height="100%" preserveAspectRatio="xMidYMid slice" width="100%" xmlns="http://www.w3.org/2000/svg">
                            <rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect>
                        </svg>
                        <div class="container">
                            <div class="carousel-caption">
                                <h1>Proyecto BlogInfo2025</h1>
                                <p class="opacity-75">Conocé más del proyecto en "Acerca de Nosotros"</p>
                                <p><a class="btn btn-lg btn-primary" href={% url "about" %}>Acerca de nosotros</a></p>
                            </div>
                        </div>
                    </div>
                    {% for publication in publications %}
                    <div class="carousel-item" style="height: 400px;">
                        <svg aria-hidden="true" class="bd-placeholder-img w-100" height="100%" preserveAspectRatio="xMidYMid slice" width="100%" xmlns="http://www.w3.org/2000/svg">
                            <rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect>
                        </svg>
                        {% if publication.image %}
                        <img src="{{ publication.image.image.url }}" class="d-block w-100 opacity-75" alt="{{ publication.title}}" style="transform: translateY(-50%);">
                        {% endif %}
                        <div class="container">
                            <div class="carousel-caption text-start">
                                <h1>{{publication.title}}</h1>
                                <p class="opacity-75">{{publication.subtitle}}</p>
                                <p class="opacity-75 text-start fst-italic">
                                    Escrito por: <a href="{% url "usuario:user" publication.author.pk %}" class="link-light">{{ publication.author.username }}</a>
                                    <br> Publicado el: {{ publication.creation_date|date:"d M, Y" }}
                                    <br> Categoría: <span class="badge bg-info text-dark">{{ publication.category }}</span>
                                </p>
                                <p><a class="btn btn-lg btn-primary" href="{% url 'noticias:ver_noticia' publication.pk %}">Leer más</a></p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="carousel-item" style="height: 400px;">
                        <svg aria-hidden="true" class="bd-placeholder-img " height="100%" preserveAspectRatio="xMidYMid slice" width="100%" xmlns="http://www.w3.org/2000/svg">
                            <rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect>
                        </svg>
                        <div class="container">
                            <div class="carousel-caption text-center">
                                <h1>¿Quieres leer más noticias?</h1>
                                <p>Mirá todas las publicaciones de nuestro sitio hacienod click aquí:</p>
                                <p><a class="btn btn-lg btn-primary" href="{% url "noticias:search_results" %}">Todas las noticias</a></p>
                            </div>
                        </div>
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
            <div class="p-5 mb-4 bg-light rounded-3">
                <div class="container-fluid py-5">
                    <h1 class="display-5 fw-bold">Bienvenido a BlogInfo2025</h1>
                    <p class="col-md-8 fs-4">Trabajo final.</p>
                    <p>Puedes acceder a todas las publicaciones haciendo click acá:</p>
                    <a href="{% url "noticias:search_results" %}" class="btn btn-primary btn-lg">Ver Todas las Noticias</a>
                </div>
            </div>
        {% endblock content %}
    </main>

    <footer class="bg-dark">
        <div class="container d-flex flex-wrap align-items-center justify-content-between py-3 my-4 text-white">
            <div class="col-md-4 d-flex align-items-center">
                <p>&copy; 2025 - Grupo 1, Comisión 2, Informatorio.</p>
            </div>
            <ul class="nav col-md-8 justify-content-end list-unstyled d-flex">
                <li class="ms-3">
                    <a class="text-body-secondary" href="https://github.com/Enzostik/Blog_Informatorio2025" aria-label="Github"><i class="fab fa-github fa-2xl" style="color: #ffffff;"></i></a>
                </li>
            </ul>
        <div>
    </footer>

    <!-- Bootstrap JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <!-- Custom JS -->
    <script src="{% static 'js/main.js' %}"></script>
    
    {% block scripts %}
    {% endblock scripts %}
</body>
</html>